In [1]:
import numpy as np

In [3]:
arr=np.zeros((1,10))

In [4]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
arr=np.ones((1,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
arr=np.zeros(10)
arr=arr+5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
arr=np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
arr=np.arange(9)
secstep=arr.reshape(3,3)
secstep

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(10)

array([0.76145558, 0.00335872, 0.18031457, 0.68585534, 0.78823205,
       0.51794957, 0.59919774, 0.00317738, 0.09756723, 0.29142386])

In [21]:
arr=np.linspace(0.1,1,99)
arr

array([0.1       , 0.10918367, 0.11836735, 0.12755102, 0.13673469,
       0.14591837, 0.15510204, 0.16428571, 0.17346939, 0.18265306,
       0.19183673, 0.20102041, 0.21020408, 0.21938776, 0.22857143,
       0.2377551 , 0.24693878, 0.25612245, 0.26530612, 0.2744898 ,
       0.28367347, 0.29285714, 0.30204082, 0.31122449, 0.32040816,
       0.32959184, 0.33877551, 0.34795918, 0.35714286, 0.36632653,
       0.3755102 , 0.38469388, 0.39387755, 0.40306122, 0.4122449 ,
       0.42142857, 0.43061224, 0.43979592, 0.44897959, 0.45816327,
       0.46734694, 0.47653061, 0.48571429, 0.49489796, 0.50408163,
       0.51326531, 0.52244898, 0.53163265, 0.54081633, 0.55      ,
       0.55918367, 0.56836735, 0.57755102, 0.58673469, 0.59591837,
       0.60510204, 0.61428571, 0.62346939, 0.63265306, 0.64183673,
       0.65102041, 0.66020408, 0.66938776, 0.67857143, 0.6877551 ,
       0.69693878, 0.70612245, 0.71530612, 0.7244898 , 0.73367347,
       0.74285714, 0.75204082, 0.76122449, 0.77040816, 0.77959

In [22]:
arr=np.arange(1,101)
arr=arr*0.01
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [23]:
mat=arr.reshape(10,10)
mat

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [24]:
z=np.linspace(0,1,20)
z

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [27]:
temp=np.arange(1,26).reshape(5,5)
temp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
temp[1:4,]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
temp[1:4,2:3]

array([[ 8],
       [13],
       [18]])

In [30]:
temp[1,2]

8

In [31]:
temp[0,]

array([1, 2, 3, 4, 5])

In [32]:
arr=temp[1,]
arr=arr+10
arr

array([16, 17, 18, 19, 20])

In [33]:
np.sum(arr)

90

In [34]:
arr.std()

1.4142135623730951