In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=pd.Series([1,2,3],[4,5,6])
arr

4    1
5    2
6    3
dtype: int64

In [3]:
arr

4    1
5    2
6    3
dtype: int64

In [37]:
dic={'Rahul':[22,23,24],'Shyam':[44,45,46],'Ram':[36,37,38]}
df=pd.DataFrame(dic)

In [38]:
df

Rahul  Shyam  Ram
0     22     44   36
1     23     45   37
2     24     46   38

In [39]:
df['Rahul']

0    22
1    23
2    24
Name: Rahul, dtype: int64

In [40]:
df[['Rahul','Ram']]

Rahul  Ram
0     22   36
1     23   37
2     24   38

In [41]:
df['Total']=df['Rahul']+df['Ram']+df['Shyam']

In [42]:
df

Rahul  Shyam  Ram  Total
0     22     44   36    102
1     23     45   37    105
2     24     46   38    108

In [50]:
df.drop('Rahul',axis=1)

Shyam  Ram  Total
0     44   36    102
1     45   37    105
2     46   38    108

In [47]:
df

Rahul  Shyam  Ram  Total
0     22     44   36    102
1     23     45   37    105
2     24     46   38    108

In [51]:
df.drop(0,axis=0)

Rahul  Shyam  Ram  Total
1     23     45   37    105
2     24     46   38    108

In [54]:
df.loc[1]

Rahul     23
Shyam     45
Ram       37
Total    105
Name: 1, dtype: int64

In [55]:
df.loc[1,'Rahul']

23

In [56]:
df

Rahul  Shyam  Ram  Total
0     22     44   36    102
1     23     45   37    105
2     24     46   38    108

In [65]:
temp=df.loc[0:2,['Rahul','Shyam']]

In [67]:
temp['newTotal']=temp['Rahul']*temp['Shyam']
temp

Rahul  Shyam  newTotal
0     22     44       968
1     23     45      1035
2     24     46      1104

In [68]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [73]:
arr[0]

0

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])