In [1]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [2]:
import numpy as np
list=[2,3,4]
list=np.array(list)
print(list)

[2 3 4]


In [3]:
import numpy as np
list=[2,3,4]
arr=np.array(list)
print(arr)

[2 3 4]


In [4]:
import numpy as np
arr=np.array([2,3,4])
print(arr)

[2 3 4]


In [5]:
import numpy as np
a=np.array([2,3,4])


In [6]:
a

array([2, 3, 4])

In [7]:
print(a)

[2 3 4]


In [8]:
list=[[1,2,3],[4,5,6]]
np.array(list)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(2)

array([1., 1.])

In [22]:
np.linspace(0,10,4)//blocks with end as difference

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:

np.random.rand(2,2)

array([[0.16347064, 0.96134232],
       [0.10591707, 0.15316791]])

In [30]:
arr=np.random.randint(1,100,20)
arr

array([18, 37, 48, 34, 12, 10, 61, 16, 55, 79, 78, 44, 78, 78, 22, 71, 93,
       74, 77, 12])

In [29]:
arr

array([2, 3, 4])

In [31]:
arr=np.random.randint(1,100,20)
arr

array([26, 82, 82, 20, 73, 79, 37, 63, 45, 39, 19, 56, 98,  9, 11, 50, 57,
       73, 59,  2])

In [34]:
arr.reshape(4,5)

array([[26, 82, 82, 20, 73],
       [79, 37, 63, 45, 39],
       [19, 56, 98,  9, 11],
       [50, 57, 73, 59,  2]])

In [35]:
arr=np.arange(1,30,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [36]:
arr[1:]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [39]:
arr[:-1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [42]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [43]:
arr.max()

29

In [44]:
arrcpy=arr.copy()
arrcpy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [45]:
arrcpy[2:5]=99
arrcpy

array([ 1,  3, 99, 99, 99, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])